### ISSUE TITLE
String interpolated with a conditional that interpolates strings breaks highlighting.

### ISSUE THREAD

**Issue by doertedev** [wholroyd/vscode-hcl#10]
![screenshot 2018-11-27 at 13 35 06](https://user-images.githubusercontent.com/1579335/49082459-19d9b580-f24a-11e8-9127-a467e876424c.png)

**Comment by wholroyd** [comment]
Looking into it.

**Comment by mijdavis2** [comment]
This also happens for strings with `/` on occasion. For example, the terminating double quotes in `key = "state/${path_relative_to_include()}/terraform.tfstate"` has the same effect as the above screenshot. Full example:

```hcl
remote_state {
  backend = "s3"
  config = {
    bucket     = "tf-state"
    key        = "state/${path_relative_to_include()}/terraform.tfstate"  ### highlighting after this line is broken in rest of the file.
    region     = "us-east-1"
    encrypt    = true
    dynamodb_table = "terraform-locks"
  }
}
```

**Comment by hoppalotta** [comment]
I am also experiencing an issue related to any string interpolation
![image](https://user-images.githubusercontent.com/59034816/96271972-1ad97480-0f93-11eb-8866-2b978d95ade7.png)
Edit: update screenshot

**Comment by wholroyd** [comment]
The ownership of this extension has been transferred to HashiCorp and its replacement can now be found at https://github.com/hashicorp/vscode-hcl. If you are interested in skipping straight to the extension for Visual Studio Code, it's available in the marketplace at https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL.

The new version will support all HashiCorp tools and will adjust its syntax based on the tool detected. In theory if you update the extension via the marketplace, you should this newer version from them automatically.
