### ISSUE TITLE
this extension prevents Terraform Snippets extensions from working

### ISSUE THREAD

**Issue by vesper8** [wholroyd/vscode-hcl#11]
When this extension is installed, the following extensions

https://github.com/run-at-scale/vscode-terraform-doc-snippets

and

https://github.com/loganarnett/vscode-tf-snippets

and

https://github.com/rixrix/vscode-terraform-snippets

will not be able to work. The snippet list will show as empty inside of a .tf file, it will even ignore user-created snippets

As soon as vscode-hcl is disabled or uninstalled, then all snippets above work

I hope you can fix this because I would like to use your extension in combination with theirs

Thanks

**Comment by wholroyd** [comment]
This extension doesn't do anything special outside of provide VSC a bag of regular extensions for color highlighting. My guess is that something happens in the editor where this extension becomes the primary provider for the file extension and no other extensions can provide their services to the same file.

Will have to investigate it.

**Comment by wholroyd** [comment]
The ownership of this extension has been transferred to HashiCorp and its replacement can now be found at https://github.com/hashicorp/vscode-hcl. If you are interested in skipping straight to the extension for Visual Studio Code, it's available in the marketplace at https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL.

The new version will support all HashiCorp tools and will adjust it's syntax based on the tool detected. In theory if you update the extension via the marketplace, you should this newer version from them automatically.
