### ISSUE TITLE
Coloring issue on {

### ISSUE THREAD

**Issue by Magicloud** [wholroyd/vscode-hcl#12]
This is terraform 0.12 validated code. The ext seems parsed the tag line wrong, as it ignores the double-quote before "k" along with "{". If I removed the "{", the line and before and after are all right. Otherwise, the "kube" string was colored as code, hence everything after that were colored inversely, code as string, string as code.

```
module "vpc" {
  # something
  tags = { "kubernetes.io/cluster/mycl" = "shared" }
}
```

**Comment by ichbestimmtnicht** [comment]
This is also somewhat true for me (in reverse...)
I am using the extension to colorcode docker-bake.hcl files. (VSCode and extension up to date)

current expected output (note: the } is missing to make this work -> not properly working)
![image](https://user-images.githubusercontent.com/28549503/109666000-0fb46900-7b6f-11eb-9a5b-7b6915a0d91c.png)

output when the missing } is set and the code works as exptected
![image](https://user-images.githubusercontent.com/28549503/109666145-34a8dc00-7b6f-11eb-8d83-f87efc7af2ca.png)

**Comment by wholroyd** [comment]
The ownership of this extension has been transferred to HashiCorp and its replacement can now be found at https://github.com/hashicorp/vscode-hcl. If you are interested in skipping straight to the extension for Visual Studio Code, it's available in the marketplace at https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL.

The new version will support all HashiCorp tools and will adjust its syntax based on the tool detected. In theory if you update the extension via the marketplace, you should this newer version from them automatically.
