### ISSUE TITLE
Coloring issue after curly brackets in double quotes

### ISSUE THREAD

**Issue by qbiqing** [wholroyd/vscode-hcl#13]
`{}` in a set of double quotes `""` disables the first quote, and the coloring acts as if the quote starts only from the second double quote, which messes up coloring for everything after this quote. Only an issue for double quote, not single quote.

**Comment by ekristen** [comment]
![Screen Shot 2020-09-01 at 9 33 19 AM](https://user-images.githubusercontent.com/48329/91873413-35030180-ec36-11ea-8590-78f9bd0d8484.png)

**Comment by JamesYeoman** [comment]
It only happens with maps. Regular blocks work fine (e.g. dynamic blocks). Notice how `Name` isn't highlighted correctly. Using strings as keys just disables highlighting altogether. I don't think the regex supports maps at all.

**Comment by wholroyd** [comment]
The ownership of this extension has been transferred to HashiCorp and its replacement can now be found at https://github.com/hashicorp/vscode-hcl. If you are interested in skipping straight to the extension for Visual Studio Code, it's available in the marketplace at https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL.

The new version will support all HashiCorp tools and will adjust its syntax based on the tool detected. In theory if you update the extension via the marketplace, you should this newer version from them automatically.
