### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by lhaig** [wholroyd/vscode-hcl#14]
Thanks for a great extension.

This issue is ore of a question:
Do you plan to include code formatting in the extension?
I sometimes get nomad job files an the format is somewhat out.
It would be good to remove extra tabs / spaces to align the sections in the code.

**Comment by wholroyd** [comment]
The ownership of this extension has been transferred to HashiCorp and its replacement can now be found at https://github.com/hashicorp/vscode-hcl. If you are interested in skipping straight to the extension for Visual Studio Code, it's available in the marketplace at https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL.

The new version will support all HashiCorp tools and will adjust its syntax based on the tool detected. In theory if you update the extension via the marketplace, you should this newer version from them automatically.
