### ISSUE TITLE
Incorrect comment handling inside {} sections

### ISSUE THREAD

**Issue by dalgibbard** [wholroyd/vscode-hcl#15]
Probably easiest to explain with pictures, but comments are not correctly handled when used within a block:

* With the current extension version from the VSCode extension page:
![highlighting1](https://user-images.githubusercontent.com/1159620/91283688-d3005300-e782-11ea-8d75-e699456f1767.png)

* With the hcl2 branch from this repo:
![highlighting3](https://user-images.githubusercontent.com/1159620/91283752-e6abb980-e782-11ea-8df3-83c0dcdfc381.png)

Thanks!

**Comment by wholroyd** [comment]
The ownership of this extension has been transferred to HashiCorp and its replacement can now be found at https://github.com/hashicorp/vscode-hcl. If you are interested in skipping straight to the extension for Visual Studio Code, it's available in the marketplace at https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL.

The new version will support all HashiCorp tools and will adjust its syntax based on the tool detected. In theory if you update the extension via the marketplace, you should this newer version from them automatically.
