### ISSUE TITLE
Add a setting to select extensions to consider or not

### ISSUE THREAD

**Issue by kral2** [wholroyd/vscode-hcl#16]
Having a setting for the VSCode extension to select which file extension should be checked or not would be great.

.tf and .tfvars files have a better highlighting support through the official terraform extension. I would like to be able to use this extension only for .hcl files.

Currently, the extension check files with these extensions `.tf .tfvars .nomad .hcl Appfile` with no option to select only some of them. This forces me to keep this extension disabled and enable it only when working on .hcl files.

**Comment by wholroyd** [comment]
The ownership of this extension has been transferred to HashiCorp and its replacement can now be found at https://github.com/hashicorp/vscode-hcl. If you are interested in skipping straight to the extension for Visual Studio Code, it's available in the marketplace at https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL.

The new version will support all HashiCorp tools and will adjust its syntax based on the tool detected. In theory if you update the extension via the marketplace, you should this newer version from them automatically.
