### ISSUE TITLE
syntax highlighting issue

### ISSUE THREAD

**Issue by travis-jorge** [wholroyd/vscode-hcl#17]
I have found an issue where the syntax highlighting is broken on the following
![SyntaxHighlightIssue](https://user-images.githubusercontent.com/80355769/114188598-4c664380-9917-11eb-861d-f82bdc37a966.PNG)

I am able to resolve this by disabling this extension. I found a similar issue for reference on the following repo for reference
https://github.com/hashicorp/vscode-terraform/issues/466

**Comment by travis-jorge** [comment]
This appears to be a duplicate

**Comment by wholroyd** [comment]
The ownership of this extension has been transferred to HashiCorp and its replacement can now be found at https://github.com/hashicorp/vscode-hcl. If you are interested in skipping straight to the extension for Visual Studio Code, it's available in the marketplace at https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL.

The new version will support all HashiCorp tools and will adjust it's syntax based on the tool detected. In theory if you update the extension via the marketplace, you should this newer version from them automatically.
