### ISSUE TITLE
Packer 1.7.4 installed, but the plugin indicates that the syntax is incorrect

### ISSUE THREAD

**Issue by 030** [wholroyd/vscode-hcl#18]
```
packer {
  required_plugins {
  }
}
```

**Comment by wholroyd** [comment]
The ownership of this extension has been transferred to HashiCorp and its replacement can now be found at https://github.com/hashicorp/vscode-hcl. If you are interested in skipping straight to the extension for Visual Studio Code, it's available in the marketplace at https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL.

The new version will support all HashiCorp tools and will adjust it's syntax based on the tool detected. In theory if you update the extension via the marketplace, you should this newer version from them automatically.
