### ISSUE TITLE
Names not recognized

### ISSUE THREAD

**Issue by PaulHatch** [wholroyd/vscode-hcl#3]
Here, everything after the opening '/*' will be highlighted as a comment:

```
path "secret/*" {
  policy = "write"
}
```

Same with a hash style comment, except just for the line:

```
path "secret/#" {
  policy = "write"
}
```

Quoted names also interfere with subsequent parse state, here even without a comment marker in the quoted name the second path isn't highlighted correctly:

```
path "secret" {
  policy = "write"
}

path "secret/foo" {
  policy = "read"
}
```

**Comment by wholroyd** [comment]
@PaulHatch Thanks for reporting the bug. I have a fix and will put this into the next release.

**Comment by wholroyd** [comment]
This will ship in v0.0.5.
