### ISSUE TITLE
meta.function.hcl scopes don't appear to handled nested blocks and interpolated strings

### ISSUE THREAD

**Issue by dleffert** [wholroyd/vscode-hcl#4]
Here is a configuration excerpt:

```hcl
######################
# configure instances
######################
resource "aws_instance" "instanceName" {
    root_block_device = {
        volume_size = "${var.auth_root_vol_size}"
        volume_type = "${var.auth_root_vol_type}"
    }
    tags {
        Name = "${var.group_name}-${var.application_name}-${var.application_version}"
    }
}
```
The line with `volume_size` has a string with an interpolated variable.  The `}` character in the string is terminating the scope of the meta.function.hcl begun on the `resource` line, causing all subsequent content to be treated as a string initiated by the `"` at the end of the `volume_size` line.

**Comment by buckyster** [comment]
Actually, if you remove the `=` after `root_block_device`, the syntax is perfect (sample 1). But if you keep the `=` after `root_block_device` and remove interpolation, the syntax is still wrong (sample 2). So is the real problem the `=` (which is a valid syntax)?

Sample 1: Correct highlighting (no `=` after `root_block_device`):
```
resource "aws_instance" "instanceName" {
    root_block_device {
        volume_size = "${var.auth_root_vol_size}"
        volume_type = "${var.auth_root_vol_type}"
    }
    tags {
        Name = "${var.group_name}-${var.application_name}-${var.application_version}"
    }
}
```

Sample 2: No interpolation (syntax still incorrect):
```
resource "aws_instance" "instanceName" {
    root_block_device = {
        volume_size = "a"
        volume_type = "b"
    }
    tags {
        Name = "c"
    }
}
```

**Comment by dleffert** [comment]
Thanks for the correction.

**Comment by buckyster** [comment]
But I do think that the highlighting rules should be fixed support the `=` as well, because it is a valid syntax.

**Comment by wholroyd** [comment]
This was written to the spec as it existed in December 2016. Looking at the HCL project (https://github.com/hashicorp/hcl), it looks like there have been some updates that need to get incorporated. I'll take a look to see what the changes were and get them incorporated if I can.
