### ISSUE TITLE
Weird colorization issue with nested arrays of objects...

### ISSUE THREAD

**Issue by klauern** [wholroyd/vscode-hcl#5]
First, let me say **thank you** for this plugin.  It's great that there actually IS a plugin for this config format at all.   That said, there's one weird issue with colorization that I thought you'd like to see or determine how possibly to fix.

The following HCL:

```hcl
resource "digitalocean_firewall" "basic-stuff" {
  name        = "BasicStuff"
  droplet_ids = ["${digitalocean_droplet.divine-smoke.id}"]

  inbound_rule = [
    {
      protocol         = "tcp"
      port_range       = "22"
      source_addresses = ["0.0.0.0/0"]
    },
    {
      protocol         = "tcp"
      port_range       = "443"
      source_addresses = ["0.0.0.0/0", "::/0"]
    },
    {
      protocol         = "tcp"
      port_range       = "9090"
      source_addresses = ["0.0.0.0/0", "::/0"]
    },
  ]

  outbound_rule = [
    {
      protocol              = "tcp"
      port_range            = "22"
      destination_addresses = ["0.0.0.0/0", "::/0"]
    },
    {
      // DNS TCP
      protocol              = "tcp"
      port_range            = "53"
      destination_addresses = ["0.0.0.0/0", "::/0"]
    },
    {
      // HTTP
      protocol              = "tcp"
      port_range            = "80"
      destination_addresses = ["0.0.0.0/0", "::/0"]
    },
    {
      // HTTPS
      protocol              = "tcp"
      port_range            = "443"
      destination_addresses = ["0.0.0.0/0", "::/0"]
    },
    {
      // DNS UDP
      protocol              = "udp"
      port_range            = "53"
      destination_addresses = ["0.0.0.0/0", "::/0"]
    },
  ]
}
```

In the context of using this for Terraform configuration, I'm working on a toy server and see that there seems to be some odd colorizing going on for the first Firewall rule on either the `inbound_rule` list or the `outbound_rule` list, so I assume it might have something to do with the first config object inside of an array:

## Inbound rule snippet

![image](https://user-images.githubusercontent.com/4735/32868224-bb1be522-ca36-11e7-8d69-60e253d2f52f.png)

## Outbound rule snippet

![image](https://user-images.githubusercontent.com/4735/32868208-a36dcf30-ca36-11e7-96c4-617db26f4d45.png)

**Comment by wholroyd** [comment]
The ownership of this extension has been transferred to HashiCorp and its replacement can now be found at https://github.com/hashicorp/vscode-hcl. If you are interested in skipping straight to the extension for Visual Studio Code, it's available in the marketplace at https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL.

The new version will support all HashiCorp tools and will adjust it's syntax based on the tool detected. In theory if you update the extension via the marketplace, you should this newer version from them automatically.
