### ISSUE TITLE
Multiple line comment block ignores quoted "/*"

### ISSUE THREAD

**Issue by hmalphettes** [wholroyd/vscode-hcl#6]
Hi and it is my turn to thank you for this extension.

The way the multiple line comment block is identified currently ignores quoted "/*":

```
# Manage auth methods broadly across Vault
path "auth/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
...
```
Everything after `"auth/*` will be a comment.

Many thanks for your attention!

**Comment by MarcoZimmermann** [comment]
Hi it works if you move the curly bace to the path row like
```
path "auth/*" {
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
```

**Comment by wholroyd** [comment]
This is the result of two things.

1. Most Terraform examples show braces starting on the same line as the construct - similar to Java, and not on a newline like you would find with CSharp. The examples are what I used to construct the syntax file for HCL at the time. Doesn't mean your method is wrong, just not what I tested for at the time.
2. There is a limitation of VSC where syntax highlighting RegEx patterns ignores my use of \s being used to attempt capturing a newline and/or return character. Looking through how the VSC team handles CSharp's next line braces, they had to considerably complicate the syntax file to handle braces on the next line.

It's fixable, but will take some time to update the syntax file to use the same method CSharp does to resolve the issue.

**Comment by wholroyd** [comment]
The ownership of this extension has been transferred to HashiCorp and its replacement can now be found at https://github.com/hashicorp/vscode-hcl. If you are interested in skipping straight to the extension for Visual Studio Code, it's available in the marketplace at https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL.

The new version will support all HashiCorp tools and will adjust its syntax based on the tool detected. In theory if you update the extension via the marketplace, you should this newer version from them automatically.
